name: CI/CD Vikash Developer

on:
  push:
    branches: ["master"] # This will run the workflow on push to master
  pull_request:
    branches: ["master"] # This will run the workflow on pull requests to master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
